[project]
name = "journalaist"
version = "0.1.0"
description = "Add a short description here"
authors = ["Ferdinand Schenck", "Axel Nordfeldt", "Jonathan Nye"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]

[dependencies]
mistralai = "==1.1.0"
streamlit = "==1.38.0"
